spring:
  application:
    name: gym-crm
  profiles:
    default: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: gym-crm

info:
  app:
    name: Gym CRM
    description: REST API for managing trainees, trainers and trainings
