spring:
  application:
    name: gym-crm
  profiles:
    default: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

security:
  oauth2:
    resourceserver:
      jwt:
        public-key-location: classpath:certs/public.pem
        private-key-location: classpath:certs/private.pem
  brute-force:
    max-attempts: 3
    block-duration-minutes: 5
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS
    allowed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: gym-crm

info:
  app:
    name: Gym CRM
    description: REST API for managing trainees, trainers and trainings
